field: fbd06c4e-0c3f-4ad5-b014-50e8db72bc84 # Amenities List
fieldLayouts:
  faad15be-e068-4dcc-9cbf-fa0efc5eb2a8:
    tabs:
      -
        elements:
          -
            fieldUid: f625ec51-6be0-4c94-a957-65f306264940 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b33bede8-4956-4ed2-96f5-203bc208448d # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b33bede8-4956-4ed2-96f5-203bc208448d: # Text
    columnSuffix: tndhfwck
    contentColumnType: string(400)
    fieldGroup: null
    handle: text
    instructions: 'Feature text input'
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: 100
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f625ec51-6be0-4c94-a957-65f306264940: # Icon
    columnSuffix: mkxbvmae
    contentColumnType: string(200)
    fieldGroup: null
    handle: icon
    instructions: 'Icon link input'
    name: Icon
    searchable: false
    settings:
      byteLimit: null
      charLimit: 50
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: feature
name: Feature
sortOrder: 1
