field: 13642bff-bb9c-4352-aaa6-ca00b85829d2
fieldLayouts:
  09f09241-2268-49ee-b11e-673e874b6cbe:
    tabs:
      -
        elements:
          -
            fieldUid: 48ba5964-ac9b-478d-961d-d7f162d4f83f
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b500bcf7-668f-4a09-abd7-a0c0a459c7b7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  48ba5964-ac9b-478d-961d-d7f162d4f83f:
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: ''
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b500bcf7-668f-4a09-abd7-a0c0a459c7b7:
    contentColumnType: string
    fieldGroup: null
    handle: linkDestination
    instructions: ''
    name: 'Link Destination'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Add a link destination'
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: navLink
name: 'Nav Link'
sortOrder: 1
