fieldLayouts:
  04252ad3-2eab-49dd-85bd-ac54851bb6ed:
    tabs:
      -
        elements:
          -
            fieldUid: f00f7ebb-f971-411a-8bd8-0975e11f0c57
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6f495b03-3811-45a4-ab47-75616a309cab
            instructions: ''
            label: 'Blog Main Text'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a8fb0957-9159-4fda-8809-4ebd81c4622b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: ''
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: 'Left Side Blog Post'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 415c6f62-6847-4640-90fe-f06351803e4c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Right Side Blog Post'
        sortOrder: 2
handle: blogPosts
hasTitleField: true
name: 'Blog Posts'
section: a81d97b8-7c53-4179-a2d4-c1df8af218d7
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
