fieldLayouts:
  4b8c01fa-1752-44b5-b8d1-0a98555ec448:
    tabs:
      -
        elements:
          -
            fieldUid: 415c6f62-6847-4640-90fe-f06351803e4c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Right Content'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 6f495b03-3811-45a4-ab47-75616a309cab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 55132d40-d27f-4468-bb43-1557d3a310da
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 2
handle: home
hasTitleField: false
name: Home
section: cfdd23c5-5a52-4224-997e-f4475bb45724
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
