fieldLayouts:
  4b8c01fa-1752-44b5-b8d1-0a98555ec448:
    tabs:
      -
        elements:
          -
            fieldUid: 415c6f62-6847-4640-90fe-f06351803e4c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Right Content'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 6f495b03-3811-45a4-ab47-75616a309cab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 55132d40-d27f-4468-bb43-1557d3a310da
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 4bb733b4-211f-47a9-bc42-258bf24d0f89 # Condo Title 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 30df8ec6-9014-4d28-8f15-ba9a922dce29 # Landing Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 71bbb603-ab4b-4ae7-9fb5-0d76c40f5ec1 # Condo Short Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 91ede8c9-d8c0-455b-a302-adcfb2121874 # Address Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Landing Header Content'
        sortOrder: 3
handle: home
hasTitleField: false
name: Home
section: cfdd23c5-5a52-4224-997e-f4475bb45724
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
