fieldLayouts:
  4b8c01fa-1752-44b5-b8d1-0a98555ec448:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 4bb733b4-211f-47a9-bc42-258bf24d0f89 # Condo Title 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 30df8ec6-9014-4d28-8f15-ba9a922dce29 # Landing Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 71bbb603-ab4b-4ae7-9fb5-0d76c40f5ec1 # Condo Short Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 91ede8c9-d8c0-455b-a302-adcfb2121874 # Address Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b6d3c6dd-f63a-48d2-9075-bb787c2e7cd0 # Image Under Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 85671307-1a72-4b4c-b41a-2d52423c2466 # Landing Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0633e114-8fcc-4023-aa72-84446cfffb98 # Open Link In
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Landing Header Content'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: c8dd77c4-a39e-423d-a678-f8aa004c246d # Gallery Item
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Image Gallery'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: cb87e7da-2460-4db1-ac7f-771c8db1a924 # Short Interest
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Short Interest'
        sortOrder: 3
handle: home
hasTitleField: false
name: Home
section: cfdd23c5-5a52-4224-997e-f4475bb45724
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
