columnSuffix: null
contentColumnType: string
fieldGroup: f5300c19-64f0-4ccd-b939-a88bf5724698
handle: amenitiesList
instructions: 'List amenities and other features available for your property'
name: 'Amenities List'
searchable: true
settings:
  contentTable: '{{%matrixcontent_amenitieslist}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
