columnSuffix: null
contentColumnType: string
fieldGroup: f5300c19-64f0-4ccd-b939-a88bf5724698
handle: shortInterest
instructions: 'This section will display 4 items below your landing image but above your photo gallery to highlight areas of your condo with a title, icon and description.'
name: 'Short Interest'
searchable: false
settings:
  contentTable: '{{%matrixcontent_shortinterest}}'
  maxBlocks: '15'
  minBlocks: '1'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
