dateModified: 1652616509
email:
  fromEmail: carr.oconnor@gmail.com
  fromName: 'Louisville Condo'
  replyToEmail: null
  template: ''
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0b25658b-1866-48e6-9b31-23f3e2280c39: Header # Header
    3fc7f2fd-503d-4c22-b99d-343c611d96c5: Image # Image
    4a93e8a5-0a43-4d07-bdc3-0f20f4a84f08: Text # Text
    4bb733b4-211f-47a9-bc42-258bf24d0f89: 'Condo Title ' # Condo Title 
    6cf4b9f8-c3a6-456d-a42c-ff3ee1607539: 'Nav Link' # Nav Link
    7b32ef01-59fc-4679-b9ac-7163dc7dd434: 'Image Description' # Image Description
    18a16d10-3678-451e-b983-cf69831295a7: Feature # Feature
    30df8ec6-9014-4d28-8f15-ba9a922dce29: 'Landing Image' # Landing Image
    37e11fd5-c2c0-4653-b271-e6e8d808bf5d: 'Featured Information' # Featured Information
    48ba5964-ac9b-478d-961d-d7f162d4f83f: 'Link Text' # Link Text
    71bbb603-ab4b-4ae7-9fb5-0d76c40f5ec1: 'Condo Short Description' # Condo Short Description
    80be797a-d96f-4f42-81ba-38d56638f4c2: test # test
    80d4b117-2dff-4449-8700-1b82cf0fcaf8: 'Enupal Slider' # Enupal Slider
    91ede8c9-d8c0-455b-a302-adcfb2121874: 'Address Label' # Address Label
    96a4443e-7c33-4e94-92fc-114ebc961d18: 'Gallery Image' # Gallery Image
    107f4ccc-bdd5-4d1c-af75-50ff56ba625b: Uploads # Uploads
    0633e114-8fcc-4023-aa72-84446cfffb98: 'Open Link In' # Open Link In
    958d76f2-cfad-45a7-963e-1743105ad752: 'Enupal Slider' # Enupal Slider
    983d981c-8052-49a0-bd18-9d0cd36b1677: 'Public Schema' # Public Schema
    13642bff-bb9c-4352-aaa6-ca00b85829d2: Navigation # Navigation
    562415a8-f8bd-4514-a7ca-cb7cc2892cdb: Link # Link
    846716b3-6db9-4ed0-9929-e813732a5c80: Title # Title
    20031374-ff5a-4edc-8455-b313b1ff8886: 'Link Url' # Link Url
    85671307-1a72-4b4c-b41a-2d52423c2466: 'Landing Video' # Landing Video
    a0334a8c-7d48-4775-9cfe-090432af78af: Html # Html
    a700da26-049b-43a9-bb7f-b0c9764325eb: Content # Content
    b0a41033-b440-4cb5-999e-76d87de0ae30: Image # Image
    b6d3c6dd-f63a-48d2-9075-bb787c2e7cd0: 'Image Under Header' # Image Under Header
    b33bede8-4956-4ed2-96f5-203bc208448d: Text # Text
    b500bcf7-668f-4a09-abd7-a0c0a459c7b7: 'Link Destination' # Link Destination
    ba1b9198-280f-4494-b9c9-7783d9ae4068: 'Interest Icon' # Interest Icon
    bc7b7788-4348-4a7e-9a1d-015a3d266633: 'Louisville Condo' # Louisville Condo
    bd950649-4585-4d1c-875f-4f12f21bfb0d: 'Interest Name' # Interest Name
    be370ed1-b13e-4b09-9f9e-043c3f10dd5d: 'Image Category' # Image Category
    c2edb73b-ea93-43ba-be28-0a2d7ffac6b1: Footer # Footer
    c8dd77c4-a39e-423d-a678-f8aa004c246d: 'Gallery Item' # Gallery Item
    c47948ee-a710-4991-a949-546994735a58: Home # Home
    cb87e7da-2460-4db1-ac7f-771c8db1a924: 'Short Interest' # Short Interest
    d2bf1a6a-d048-4b95-bbc1-55c043f424ca: Interest # Interest
    d346521f-ef39-4eb6-8973-af9208a0d910: Feature # Feature
    e0356e54-854a-44a2-bf30-d368c7965eb6: Image # Image
    e5152d9c-f61e-4c07-ba06-53053a65857b: 'Interest Description' # Interest Description
    f625ec51-6be0-4c94-a957-65f306264940: Icon # Icon
    fbd06c4e-0c3f-4ad5-b014-50e8db72bc84: 'Amenities List' # Amenities List
plugins:
  enupal-slider:
    enabled: true
    licenseKey: OJ9622LY2OEQJ4KNCFI2SSS5
    settings:
      htmlHandle: enupalSliderHtml
      linkHandle: enupalSliderLink
      loadJquery: 1
      openLinkHandle: enupalSliderOpenLink
      pluginNameOverride: ''
      volumeId: 2
      volumeUid: 80d4b117-2dff-4449-8700-1b82cf0fcaf8 # Enupal Slider
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-font-awesome:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
system:
  edition: pro
  live: true
  name: 'Louisville Condo'
  retryDuration: null
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
