dateModified: 1615173197
email:
  fromEmail: carr.oconnor@gmail.com
  fromName: 'Test Site'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: 'Test Site'
  schemaVersion: 3.5.13
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
