fieldLayouts:
  2c57d1bf-7995-4562-b34b-38c3ee128fc4:
    tabs:
      -
        elements:
          -
            fieldUid: 6f495b03-3811-45a4-ab47-75616a309cab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: footer
name: Footer
