enableVersioning: true
handle: aboutUs
name: 'About Us'
propagationMethod: all
siteSettings:
  bc7b7788-4348-4a7e-9a1d-015a3d266633: # Louisville Condo
    enabledByDefault: true
    hasUrls: true
    template: general
    uriFormat: about-us
type: single
