enableVersioning: true
handle: blog
name: Blog
propagationMethod: all
siteSettings:
  bc7b7788-4348-4a7e-9a1d-015a3d266633:
    enabledByDefault: true
    hasUrls: true
    template: blog/index
    uriFormat: blog
type: single
