enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  bc7b7788-4348-4a7e-9a1d-015a3d266633: # Louisville Condo
    enabledByDefault: true
    hasUrls: true
    template: home
    uriFormat: __home__
type: single
